jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./src/API/deploy.sh
         ./src/API/deploy.sh ${{ APP_VERSION }}
      shell: bash
      env:
	    - AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
	    - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   	  - AWS_Account_ID: ${{ secrets.AWS_Account_ID }}
	    - AWS_DEFAULT_REGION: 'us-east-1'
	    - APP_VERSION: ${{ secrets.APP_VERSION}}